///////////////////////////////////////////////////////////
//  CBaseMissile.as
//  Macromedia ActionScript Implementation of the Class CBaseMissile
//  Generated by Enterprise Architect
//  Created on:      14-Dec-2010 2:03:34 PM
//  Original author: Kurniawan Fitriadi
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.ai.AIState_Enemy_Hit;
	import flash.display.DisplayObjectContainer;
	import flash.display.MovieClip;
	/**
	 * @author Kurniawan Fitriadi
	 * @version 1.0
	 * @created 14-Dec-2010 2:03:34 PM
	 */
	
	public class CBaseMissile
	{
		public var prev:CBaseMissile;
		public var next:CBaseMissile;
		
		
	    protected var m_faction: int;
	    protected var m_damage: int;
	    protected var m_speed: Number;
		protected var m_lane: int;
		protected var m_direction: int;
		
		protected var m_counterOf:int;
		protected var m_counterDamage:int;
		protected var m_level:int;
		
		protected var m_sprite:MovieClip;
		protected var m_container:DisplayObjectContainer;
		
		protected var m_active:Boolean;
		protected var m_detectInvisible:Boolean;
		
		protected var m_owner:CBaseTeelos;
		
		public function CBaseMissile()
		{
			initialize();
		}
		
		public function initialize():void
		{
			m_damage = 4;
			m_speed = 0.15;
			m_detectInvisible = false;
		}
		
		public function isActive():Boolean
		{
			return m_active;
		}
		
		public function onCreate( container:DisplayObjectContainer, x:int, y:int, direction:int, 
								  faction:int, lane:int, 
								  damage:int, counterOf:int, counterDamage:int,
								  level:int, detectInvisible:Boolean, owner:CBaseTeelos, exParams:Object = null ):void
		{	
			
			m_container = container;
			m_container.addChild( m_sprite );
			
			m_owner = owner;
			m_detectInvisible = detectInvisible;
			
			m_sprite.x = x;
			m_sprite.y = y;
		
			m_sprite.scaleX = m_direction = direction;
			
			m_faction = faction;
			m_lane = lane;
			
			m_damage = damage;
			m_counterOf = counterOf;
			m_counterDamage = counterDamage;
			m_level = level;
			
			m_active = true;
		}
		
		public function onRemove():void
		{
			m_container.removeChild( m_sprite );
		}
		
		protected function onHit(target:CBaseTeelos):void
		{
			//play sfx
			SoundManager.getInstance().playSFX("SN13");
			
			var bonus:int = ( m_counterOf == target.unitClass ) ? m_counterDamage : 0;
			target.damage( m_damage + m_level + bonus, m_owner );
		}
		
		public function move(elapsedTime:int):void
		{
			// ABSTRACT METHOD
		}
		
		public function update(elapsedTime:int):void
		{
			move(elapsedTime);
		}
	}//end CBaseMissile
}