///////////////////////////////////////////////////////////
//  CBasePickableItem.as
//  Macromedia ActionScript Implementation of the Class CBasePickableItem
//  Generated by Enterprise Architect
//  Created on:      15-Des-2010 20:48:34
//  Original author: poof!
///////////////////////////////////////////////////////////

package com.game
{
	import flash.display.DisplayObjectContainer;
	import flash.display.MovieClip;
	import flash.events.MouseEvent;
	import flash.ui.Mouse;
	
	/**
	 * @author poof!
	 * @version 1.0
	 * @created 15-Des-2010 20:48:34
	 */
	public class CBasePickableItem
	{
	    public var prev: CBasePickableItem;
	    public var next: CBasePickableItem;
		
		protected var m_container:DisplayObjectContainer;
	    protected var m_active: Boolean;
	    protected var m_maxLifetime: int;
	    protected var m_currLifetime: int;
	    protected var m_floorBound: int;
		protected var m_sprite: MovieClip;
		
		public function CBasePickableItem(){
			initialize();
		}

	    public function initialize(): void
	    {
			m_maxLifetime = 10000;
	    }
		
		public function onCreate(container:DisplayObjectContainer, x:int, y:int, floorBound:int):void
		{
			m_container = container;
			m_container.addChild(m_sprite);
			
			m_sprite.x = x;
			m_sprite.y = y;
			m_floorBound = floorBound;
			
			m_currLifetime = 0;
			m_sprite.addEventListener(MouseEvent.MOUSE_OVER, onPicked);
			
			m_active = true;
		}
		
		public function onRemove():void
		{
			m_sprite.removeEventListener(MouseEvent.MOUSE_OVER, onPicked);
			m_container.removeChild(m_sprite);
		}
		
		protected function onPicked(event:MouseEvent):void
		{
			// ABSTRACT METHOD
			m_active = false;
		}

	    public function isActive(): Boolean
	    {
			return m_active;
	    }

	    /**
	     * 
	     * @param elapsedTime
	     */
	    public function update(elapsedTime:int): void
	    {
			m_currLifetime += elapsedTime;
			if( m_currLifetime > m_maxLifetime )
				m_active = false;
	    }

	}//end CBasePickableItem

}