///////////////////////////////////////////////////////////
//  CItemCoin.as
//  Macromedia ActionScript Implementation of the Class CItemCoin
//  Generated by Enterprise Architect
//  Created on:      15-Des-2010 20:48:41
//  Original author: poof!
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.CBasePickableItem;
	import com.greensock.easing.Bounce;
	import com.greensock.TweenMax;
	import flash.display.DisplayObjectContainer;
	import flash.events.MouseEvent;

	/**
	 * @author poof!
	 * @version 1.0
	 * @created 15-Des-2010 20:48:41
	 */
	public class CItem_SilverCoin extends CBasePickableItem
	{
		public function CItem_SilverCoin(){
			
		}
		
		override public function initialize():void 
		{
			super.initialize();
			m_sprite = new mcCoin();
			m_sprite.scaleX = m_sprite.scaleY = 2;
			
			
		}
		
		override public function onCreate(container:DisplayObjectContainer, x:int, y:int, floorBound:int):void 
		{
			super.onCreate( container, x, y, floorBound );
			
			m_sprite.alpha = 1;
			TweenMax.to(m_sprite, 0.25, {colorMatrixFilter:{colorize:0xffffff, amount:1}});
			TweenMax.to( m_sprite, 1, { y:m_floorBound, ease:Bounce.easeOut } );
		}
		
		override public function onRemove():void 
		{
			TweenMax.killTweensOf( m_sprite );
			super.onRemove();
		}
		
		override protected function onPicked(event:MouseEvent):void 
		{
			SoundManager.getInstance().playSFX("SNCoin");
			TweenMax.killTweensOf( m_sprite );
			TweenMax.to( m_sprite, 0.7, { x:120, y:95, alpha:0.1, 
										  onComplete:function():void 
										  { 
											  m_active = false;
											  GlobalVars.TOTAL_COIN += 5;
											  State_GameLoop.getInstance().invalidateGold();
										  } 
										} );
		}

	}//end CItemCoin

}