///////////////////////////////////////////////////////////
//  CMissileArrow_Croztan.as
//  Macromedia ActionScript Implementation of the Class CMissileArrow_Croztan
//  Generated by Enterprise Architect
//  Created on:      20-Des-2010 0:40:42
//  Original author: poof!
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.CBaseLinearMissile;
	import com.game.CBaseTeelos;
	import flash.display.DisplayObjectContainer;

	/**
	 * @author poof!
	 * @version 1.0
	 * @created 20-Des-2010 0:40:42
	 */
	public class CMissileArrow_Croztan extends CBaseLinearMissile
	{
		public function CMissileArrow_Croztan(){

		}
		
		override public function initialize():void 
		{
			super.initialize();
			
			m_speed = 0.32;
			m_sprite = new mcArrow_Croztan();
			m_sprite.cacheAsBitmap = true;
		}
		
		override public function onCreate( container:DisplayObjectContainer, x:int, y:int, 
										   direction:int, faction:int, lane:int, damage:int, 
										   counterOf:int, counterDamage:int, level:int, detectVisible:Boolean,
										   owner:CBaseTeelos, exParams:Object = null):void 
		{
			//sound fx play
			SoundManager.getInstance().playSFX("SN07");
			
			super.onCreate(container, x, y, direction, faction, lane, damage, counterOf, 
						   counterDamage, level, detectVisible, owner, exParams);
		}
		
		override protected function onHit(target:CBaseTeelos):void 
		{
			super.onHit(target);
			m_targetTimes--;
		}
	}//end CMissileArrow_Croztan

}