///////////////////////////////////////////////////////////
//  CMissileArrow_Feela.as
//  Macromedia ActionScript Implementation of the Class CMissileArrow_Feela
//  Generated by Enterprise Architect
//  Created on:      14-Dec-2010 3:28:58 PM
//  Original author: Kurniawan Fitriadi
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.CBaseLinearMissile;
	import com.game.CBaseTeelos;
	import flash.display.DisplayObjectContainer;

	/**
	 * @author Kurniawan Fitriadi
	 * @version 1.0
	 * @created 14-Dec-2010 3:28:58 PM
	 */
	public class CMissileBallista_Balistatoz extends CBaseLinearMissile
	{
		private var m_victims:Array;
		
		public function CMissileBallista_Balistatoz(){
		}
		
		override public function initialize():void 
		{
			super.initialize();
			
			m_victims = [];
			
			m_speed = 0.32;
			m_sprite = new mcBallista_Balistatoz();
			m_sprite.cacheAsBitmap = true;
		}
		
		override public function onCreate(container:DisplayObjectContainer, x:int, y:int, direction:int, faction:int, lane:int, damage:int, counterOf:int, counterDamage:int, level:int, detectInvisible:Boolean, owner:CBaseTeelos, exParams:Object = null):void 
		{
			super.onCreate(container, x, y, direction, faction, lane, damage, counterOf, counterDamage, level, detectInvisible, owner, exParams);
			
			m_targetTimes = 3;
			if( m_victims )
				m_victims.splice(0, m_victims.length);
		}
		
		override protected function onHit(target:CBaseTeelos):void 
		{
			if ( m_victims.indexOf(target) < 0 )
			{
				m_victims.push(target);
				m_targetTimes--;
			}
			
			super.onHit(target);
		}
		
		override public function onRemove():void 
		{
			super.onRemove();
		}
	}

}