///////////////////////////////////////////////////////////
//  CTeeloCroztan.as
//  Macromedia ActionScript Implementation of the Class CTeeloCroztan
//  Generated by Enterprise Architect
//  Created on:      20-Des-2010 0:33:28
//  Original author: poof!
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.ai.AIState;
	import com.game.CEnemyTeelos;
	import flash.display.DisplayObjectContainer;
	import math.OpMath;
	import utils.Utility;

	/**
	 * @author poof!
	 * @version 1.0
	 * @created 20-Des-2010 0:33:28
	 */
	public class CTeeloHestaclan extends CEnemyTeelos implements IRangeAttacker
	{
		public function CTeeloHestaclan(){

		}
		
		override public function initialize():void 
		{
			super.initialize();
			
			m_attack = 3;
			m_defense = 5;
			m_maxLife = 12;
			m_unitClass = UNITCLASS.ARCHER;
			m_counterClass = UNITCLASS.INFANTRY;
			m_counterBonus = 2;
			m_baseSpeed = 0.05;
			m_dropMin = 1;
			m_dropMax = 4;
			m_baseCooldownTime = 4000;
		}
		
		override public function onCreate(lane:int, targetPosX:int, container:DisplayObjectContainer):void 
		{
			super.onCreate(lane, targetPosX, container);
			m_attackRange = 300;
		}
		
		override protected function createSprite():void 
		{
			super.createSprite();
			m_sprite = new mcTeelo_Hestaclan();
		}
		
		override public function releaseProjectile():void
		{
			super.releaseProjectile();
			
			var enemy:Array = NPCManager.getInstance().getListOfUnit(m_lane, NPCManager.FACTION_PLAYER);
			
			if ( enemy )
			{
				var pool:Array = Utility.copyArray(enemy);
				
				for ( var i:int = 0; i < 2; i++ )
				{
					if ( pool.length > 0 )
					{
						var hitIndex:int = Math.floor( OpMath.randomRange(0, pool.length - 1) );
						var hitTarget:CBaseTeelos = pool[hitIndex];
						
						if ( hitTarget && !(hitTarget is CTeeloLastBarricade) )
						{
							pool.splice(hitIndex, 1);
							MissileManager.getInstance().launch( CMissileArrow_Hestaclan, m_container, m_sprite.x, m_sprite.y - 45, 
																 1, getFaction(), m_lane,
																 m_attack, m_counterClass, m_counterBonus, m_level, m_detectInvisible, this,
																 {target:hitTarget, groundLevel:y } );
						}
					}
				}
			}
		}
	}//end CTeeloCroztan

}