///////////////////////////////////////////////////////////
//  CTeeloAgeesum.as
//  Macromedia ActionScript Implementation of the Class CTeeloAgeesum
//  Generated by Enterprise Architect
//  Created on:      19-Des-2010 16:51:23
//  Original author: poof!
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.CBaseTeelos;
	import com.game.CPlayerTeelos;
	import flash.display.DisplayObjectContainer;
	import math.OpMath;
	import com.game.fx.CEffect_Summon;

	/**
	 * @author poof!
	 * @version 1.0
	 * @created 19-Des-2010 16:51:23
	 */
	public class CTeeloAgeesum extends CPlayerTeelos implements IRangeAttacker
	{
		public function CTeeloAgeesum(){

		}
		
		override public function initialize():void 
		{
			super.initialize();
			
			m_attack = 5;
			m_defense = 5;
			m_maxLife = 10;
			m_unitClass = UNITCLASS.MAGE;
			m_counterClass = UNITCLASS.NONE;
			m_counterBonus = 0;
			m_baseSpeed = 0.07;
			m_baseCooldownTime = 22000;
			m_trainCost = 600;
		}
		
		override protected function createSprite():void 
		{
			super.createSprite();
			m_sprite = new mcTeelo_Ageesum();
		}
		
		override public function onCreate(lane:int, targetPosX:int, container:DisplayObjectContainer):void 
		{
			super.onCreate(lane, targetPosX, container);
			m_attackRange = 800;
		}
		
		override public function attack(target:CBaseTeelos):void 
		{
			m_target = target;
			if ( !isCoolingDown() )
			{ 
				m_cooldownCounter = 0;
				var dice:int = OpMath.randomNumber(6);
				var frame:int = ( dice < 3 ) ? 4 : 5;
				m_sprite.gotoAndStop(frame);
				animationReset();
				
				// summon
				
				var summon:CTeeloBaseSummoned = CTeeloBaseSummoned(NPCManager.getInstance().add(CTeeloSummonedLevel02, m_lane, 1000, m_container));
				summon.x = x + 10;
				ParticleManager.getInstance().add(CEffect_Summon, summon.x, summon.y);
				summon.owner = this;
			}
			else
			{
				if( m_sprite.currentFrame != 1 )
				{
					m_sprite.gotoAndStop(1);
					animationReset();
				}
			}
		}
	}//end CTeeloAgeesum

}