///////////////////////////////////////////////////////////
//  CTeeloFeela.as
//  Macromedia ActionScript Implementation of the Class CTeeloFeela
//  Generated by Enterprise Architect
//  Created on:      14-Dec-2010 3:02:06 PM
//  Original author: poof!
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.ai.AIState;
	import com.game.CPlayerTeelos;
	import flash.display.DisplayObjectContainer;

	/**
	 * @author poof!
	 * @version 1.0
	 * @created 14-Dec-2010 3:02:06 PM
	 */
	public class CTeeloFeela extends CPlayerTeelos implements IRangeAttacker
	{
		public function CTeeloFeela(){

		}
		
		override public function initialize():void 
		{
			super.initialize();
			
			m_attack = 2;
			m_defense = 5;
			m_maxLife = 10;
			m_unitClass = UNITCLASS.ARCHER;
			m_counterClass = UNITCLASS.INFANTRY;
			m_counterBonus = 1;
			m_baseSpeed = 0.1;
			m_baseCooldownTime = 1800;
			m_trainCost = 180;
		}
		
		override public function onCreate(lane:int, targetPosX:int, container:DisplayObjectContainer):void 
		{
			super.onCreate(lane, targetPosX, container);
			m_attackRange = 700;
		}
		
		override protected function createSprite():void 
		{
			super.createSprite();
			m_sprite = new mcTeelo_Feela();
		}
		
		override public function releaseProjectile():void
		{
			super.releaseProjectile();
			MissileManager.getInstance().launch( CMissileArrow_Feela, m_container, m_sprite.x, m_sprite.y - 45, 
												 m_sprite.scaleX, getFaction(), m_lane,
												 m_attack, m_counterClass, m_counterBonus, m_level, m_detectInvisible, this );
		}
	}//end CTeeloFeela

}