///////////////////////////////////////////////////////////
//  CTeeloSeeldy.as
//  Macromedia ActionScript Implementation of the Class CTeeloSeeldy
//  Generated by Enterprise Architect
//  Created on:      16-Dec-2010 3:44:41 PM
//  Original author: poof!
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.CBaseTeelos;
	import com.game.CPlayerTeelos;

	/**
	 * @author poof!
	 * @version 1.0
	 * @created 16-Dec-2010 3:44:41 PM
	 */
	public class CTeeloSeeldy extends CPlayerTeelos
	{
		public function CTeeloSeeldy(){

		}
		
		override public function initialize():void 
		{
			super.initialize();
			
			super.initialize();
			
			m_attack = 0;
			m_defense = 20;
			m_maxLife = 75;
			m_unitClass = UNITCLASS.INFANTRY;
			m_counterClass = UNITCLASS.NONE;
			m_counterBonus = 0;
			m_baseSpeed = 0.04;
			m_baseCooldownTime = 1100;
			m_trainCost = 200;
		}
		
		override protected function createSprite():void 
		{
			super.createSprite();
			m_sprite = new mcTeelo_Seeldy();
		}
		
		override public function attack(target:CBaseTeelos):void 
		{
			// none
		}

	}//end CTeeloSeeldy

}