///////////////////////////////////////////////////////////
//  CTeeloBaseSummoned.as
//  Macromedia ActionScript Implementation of the Class CTeeloBaseSummoned
//  Generated by Enterprise Architect
//  Created on:      19-Des-2010 17:47:44
//  Original author: poof!
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.CPlayerTeelos;
	import math.OpMath;

	/**
	 * @author poof!
	 * @version 1.0
	 * @created 19-Des-2010 17:47:44
	 */
	public class CTeeloBaseSummoned extends CPlayerTeelos
	{
		private var m_owner:CBaseTeelos;
		
		public function CTeeloBaseSummoned(){

		}
		
		public function set owner(value:CBaseTeelos):void
		{
			m_owner = value;
		}
		
		public function get owner():CBaseTeelos
		{
			return m_owner;
		}
		
		override public function update(elapsedTime:int):void 
		{
			super.update(elapsedTime);
			
			if ( m_active && x > 820 )
			{
				m_active = false;
			}
		}
		
		override public function attack(target:CBaseTeelos):void 
		{
			if ( !isCoolingDown() )
			{
				m_cooldownCounter = 0;
				var dice:int = OpMath.randomNumber(6);
				var frame:int = ( dice < 3 ) ? 4 : 5;
				m_sprite.gotoAndStop(frame);
				animationReset();
				
				if ( !(target is CTeeloTeegor) && 
					 !(target is CTeeloBalistatoz) && 
					 !(target is CTeeloRammer) )
					CEnemyTeelos(target).splat();
			}
			else
			{
				if( m_sprite.currentFrame != 1 )
				{
					m_sprite.gotoAndStop(1);
					animationReset();
				}
			}
		}
	}//end CTeeloBaseSummoned

}