///////////////////////////////////////////////////////////
//  CTeeloCroztan.as
//  Macromedia ActionScript Implementation of the Class CTeeloCroztan
//  Generated by Enterprise Architect
//  Created on:      20-Des-2010 0:33:28
//  Original author: poof!
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.ai.AIState;
	import com.game.CEnemyTeelos;
	import flash.display.DisplayObjectContainer;

	/**
	 * @author poof!
	 * @version 1.0
	 * @created 20-Des-2010 0:33:28
	 */
	public class CTeeloCroztan extends CEnemyTeelos implements IRangeAttacker
	{
		public function CTeeloCroztan(){

		}
		
		override public function initialize():void 
		{
			super.initialize();
			
			m_attack = 1;
			m_defense = 1;
			m_maxLife = 3;
			m_unitClass = UNITCLASS.ARCHER;
			m_counterClass = UNITCLASS.INFANTRY;
			m_counterBonus = 1;
			m_baseSpeed = 0.05;
			m_dropMin = 0;
			m_dropMax = 2;
			m_baseCooldownTime = 2000;
		}
		
		override public function onCreate(lane:int, targetPosX:int, container:DisplayObjectContainer):void 
		{
			super.onCreate(lane, targetPosX, container);
			m_attackRange = 300;
		}
		
		override protected function createSprite():void 
		{
			super.createSprite();
			m_sprite = new mcTeelo_Croztan();
		}
		
		override public function releaseProjectile():void
		{
			super.releaseProjectile();
			MissileManager.getInstance().launch( CMissileArrow_Croztan, m_container, m_sprite.x, m_sprite.y - 45, 
												 m_sprite.scaleX, getFaction(), m_lane,
												 m_attack, m_counterClass, m_counterBonus, m_level, m_detectInvisible, this );
		}

	}//end CTeeloCroztan

}