///////////////////////////////////////////////////////////
//  CTeeloUdizark.as
//  Macromedia ActionScript Implementation of the Class CTeeloUdizark
//  Generated by Enterprise Architect
//  Created on:      20-Des-2010 0:11:06
//  Original author: poof!
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.CEnemyTeelos;

	/**
	 * @author poof!
	 * @version 1.0
	 * @created 20-Des-2010 0:11:06
	 */
	public class CTeeloUdizark extends CEnemyTeelos
	{
		public function CTeeloUdizark(){

		}
		
		override public function initialize():void 
		{
			super.initialize();
			m_attack = 20;
			m_defense = 10;
			m_maxLife = 100;
			m_unitClass = UNITCLASS.CAVALRY;
			m_counterClass = UNITCLASS.ARCHER;
			m_counterBonus = 3;
			m_baseSpeed = 0.01;
			m_dropMin = 4;
			m_dropMax = 6;
			m_baseCooldownTime = 1200;
		}
		
		override protected function createSprite():void 
		{
			super.createSprite();
			m_sprite = new mcTeelo_Udizark();
		}
		
		override public function animationHit():void 
		{
			// no animation
		}

	}//end CTeeloUdizark

}