///////////////////////////////////////////////////////////
//  CTeeloTeeclon.as
//  Macromedia ActionScript Implementation of the Class CTeeloTeeclon
//  Generated by Enterprise Architect
//  Created on:      19-Des-2010 23:52:00
//  Original author: poof!
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.CEnemyTeelos;

	/**
	 * @author poof!
	 * @version 1.0
	 * @created 19-Des-2010 23:52:00
	 */
	public class CTeeloTeeclon extends CEnemyTeelos
	{
		public function CTeeloTeeclon(){}
		
		override public function initialize():void 
		{
			super.initialize();
			
			m_attack = 8;
			m_defense = 8;
			m_maxLife = 30;
			m_unitClass = UNITCLASS.CAVALRY;
			m_counterClass = UNITCLASS.ARCHER;
			m_counterBonus = 2;
			m_baseSpeed = 0.05;
			m_dropMin = 3;
			m_dropMax = 4;
			m_baseCooldownTime = 1200;
		}
		
		override protected function createSprite():void 
		{
			super.createSprite();
			m_sprite = new mcTeelo_Teeclon();
		}
		
		override public function animationHit():void 
		{
			// no animation
		}
	}//end CTeeloTeeclon

}