///////////////////////////////////////////////////////////
//  CTeeloRazark.as
//  Macromedia ActionScript Implementation of the Class CTeeloRazark
//  Generated by Enterprise Architect
//  Created on:      19-Des-2010 23:00:01
//  Original author: poof!
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.ai.AIState;
	import com.game.CEnemyTeelos;

	/**
	 * @author poof!
	 * @version 1.0
	 * @created 19-Des-2010 23:00:01
	 */
	public class CTeeloRazark extends CEnemyTeelos
	{
		public function CTeeloRazark(){

		}
		
		override public function initialize():void 
		{
			super.initialize();
			
			m_attack = 8;
			m_defense = 6;
			m_maxLife = 25;
			m_unitClass = UNITCLASS.INFANTRY;
			m_counterClass = UNITCLASS.NONE;
			m_counterBonus = 0;
			m_baseSpeed = 0.02;
			m_dropMin = 0;
			m_dropMax = 3;
			m_baseCooldownTime = 1800;
		}
		
		override protected function createSprite():void 
		{
			super.createSprite();
			m_sprite = new mcTeelo_Razark();
		}
	}//end CTeeloRazark
}