///////////////////////////////////////////////////////////
//  CTeeloWorkerReturn.as
//  Macromedia ActionScript Implementation of the Class CTeeloWorkerReturn
//  Generated by Enterprise Architect
//  Created on:      22-Dec-2010 11:42:28 AM
//  Original author: Kurniawan Fitriadi
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.ai.AIState_Worker_Home;
	import com.game.CPlayerTeelos;
	import flash.display.DisplayObjectContainer;

	/**
	 * @author Kurniawan Fitriadi
	 * @version 1.0
	 * @created 22-Dec-2010 11:42:28 AM
	 */
	public class CTeeloWorkerReturn extends CPlayerTeelos implements IInvulnerable
	{
		public function CTeeloWorkerReturn(){

		}

		override public function initialize():void 
		{
			super.initialize();
			
			m_attack = 0;
			m_defense = 5;
			m_maxLife = 10;
			m_unitClass = UNITCLASS.WORKER;
			m_counterClass = UNITCLASS.NONE;
			m_counterBonus = 0;
			m_baseSpeed = 0.1;
			m_baseCooldownTime = 1800;
		}
		
		override public function onCreate(lane:int, targetPosX:int, container:DisplayObjectContainer):void 
		{
			super.onCreate( lane, targetPosX, container );
			setDestination(-100);
			changeAIState( AIState_Worker_Home.getInstance() );
		}
		
		override protected function createSprite():void 
		{
			super.createSprite();
			m_sprite = new mcTeelo_WorkerHome();
		}
	}//end CTeeloWorkerReturn

}