///////////////////////////////////////////////////////////
//  CTeeloBallistaTower.as
//  Macromedia ActionScript Implementation of the Class CTeeloBallistaTower
//  Generated by Enterprise Architect
//  Created on:      21-Dec-2010 3:21:49 PM
//  Original author: poof!
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.ai.AIState_Player_Ballista_Die;
	import com.game.ai.AIState_Player_Ballista_Enter;
	import com.game.CBaseTeelos;
	import com.game.CTeeloBaseBuilding;
	import flash.display.DisplayObjectContainer;

	/**
	 * @author poof!
	 * @version 1.0
	 * @created 21-Dec-2010 3:21:50 PM
	 */
	public class CTeeloBallistaTower extends CTeeloBaseBuilding implements IRangeAttacker
	{
		public function CTeeloBallistaTower(){

		}

		override public function initialize():void 
		{
			super.initialize();
			
			m_attack = 15;
			m_defense = 0;
			m_maxLife = 20;
			m_unitClass = UNITCLASS.BUILDING;
			m_counterClass = UNITCLASS.NONE;
			m_counterBonus = 0;
			m_baseSpeed = 0.05;
			m_baseCooldownTime = 15000;
			m_trainCost = 2000;
			
		}
		
		override protected function createSprite():void 
		{
			super.createSprite();
			m_sprite = new mcTeelo_DefendTower();
		}
		
		override public function releaseProjectile():void
		{
			super.releaseProjectile();
			MissileManager.getInstance().launch( CMissileBallista_Tower, m_container, m_sprite.x, m_sprite.y - 50, 
												 1, getFaction(), m_lane,
												 m_attack, m_counterClass, m_counterBonus, m_level, m_detectInvisible, this );
		}
		
		override public function onCreate(lane:int, targetPosX:int, container:DisplayObjectContainer):void 
		{
			super.onCreate(lane, targetPosX, container);
			m_attackRange = 800;
			changeAIState( AIState_Player_Ballista_Enter.getInstance() );
		}
		
		override public function damage(value:int, source:CBaseTeelos):void 
		{
			if ( value > 0 )
			{
				var def:int = Math.ceil( defense / 2 );
				var dmg:int = (def > value) ? 1 : value - def;
			}
			else
			{
				dmg = value;
			}
			if (dmg == 0) dmg = 1;
			
			m_currLife -= dmg;
			if( m_currLife < 0 )
			{
				m_dead = true;
				changeAIState( AIState_Player_Ballista_Die.getInstance() );
			}
			
			m_currLife = Math.min(m_currLife, m_maxLife);		// cap value when unit is healed
			
			// tint sprite
			var col:int = (value > 0) ? 0xFF0000 : 0x00FF00;
			tintOnHit(col);
		}
		
		override public function attack(target:CBaseTeelos):void 
		{
			m_target = target;
			trace("Attempting Attack");
			
			if ( !isCoolingDown() )
			{
				trace("attack success");
				m_cooldownCounter = 0;
				m_sprite.gotoAndStop(4);
				animationReset();
			}
			else trace("attack fail cooling down");
		}
	}//end CTeeloBallistaTower

}