///////////////////////////////////////////////////////////
//  CTeeloPoztazark.as
//  Macromedia ActionScript Implementation of the Class CTeeloPoztazark
//  Generated by Enterprise Architect
//  Created on:      21-Dec-2010 4:07:55 PM
//  Original author: poof!
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.CEnemyTeelos;
	import com.game.fx.CEffect_Heal;
	import flash.display.DisplayObjectContainer;

	/**
	 * @author poof!
	 * @version 1.0
	 * @created 21-Dec-2010 4:07:55 PM
	 */
	public class CTeeloPoztazark extends CEnemyTeelos
	{
		public function CTeeloPoztazark(){

		}
		
		override public function initialize():void 
		{
			super.initialize();
			
			m_attack = -25; //siom, 23jan011 12:09
			m_defense = 3;
			m_maxLife = 55; //siom, 23jan011 12:09
			m_unitClass = UNITCLASS.MAGE;
			m_counterClass = UNITCLASS.NONE;
			m_counterBonus = 0;
			m_baseSpeed = 0.07;
			m_dropMin = 6;
			m_dropMax = 8;
			m_baseCooldownTime = 5000;
		}
		
		override protected function createSprite():void 
		{
			super.createSprite();
			m_sprite = new mcTeelo_Poztazark();
		}
		
		override public function onCreate(lane:int, targetPosX:int, container:DisplayObjectContainer):void 
		{
			super.onCreate(lane, targetPosX, container);
			
			setDestination(720); //siom, 23jan011 12:12
			m_attackRange = 10;
		}
		
		override public function attack(target:CBaseTeelos):void 
		{
			m_target = target;
			
			if ( !isCoolingDown() )
			{
				m_cooldownCounter = 0;
				
				//play sfx
				SoundManager.getInstance().playSFX("SN11");
				
				var amount:Number = target.maxLife * 0.1;
				target.damage( -amount, this );
				
				ParticleManager.getInstance().add(CEffect_Heal, target.x, target.y);
			}
			else
			{
				if( m_sprite.currentFrame != 1 )
				{
					m_sprite.gotoAndStop(1);
					animationReset();
				}
			}
		}
		
		

	}//end CTeeloPoztazark

}