///////////////////////////////////////////////////////////
//  CTeeloTeemy.as
//  Macromedia ActionScript Implementation of the Class CTeeloTeemy
//  Generated by Enterprise Architect
//  Created on:      11-Des-2010 22:24:45
//  Original author: poof!
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.CPlayerTeelos;
	import flash.display.DisplayObjectContainer;

	/**
	 * @author poof!
	 * @version 1.0
	 * @created 11-Des-2010 22:24:45
	 */
	public class CTeeloTeemy extends CPlayerTeelos
	{
		private var m_bashInitiated:Boolean;
		
		public function CTeeloTeemy(){

		}
		
		override public function initialize():void 
		{
			super.initialize();
			
			m_attack = 4;
			m_defense = 6;
			m_maxLife = 18;
			m_unitClass = UNITCLASS.INFANTRY;
			m_counterClass = UNITCLASS.INFANTRY;
			m_counterBonus = 3;
			m_baseSpeed = 0.1;
			m_baseCooldownTime = 1100;
			m_trainCost = 25;
		}
		
		override protected function createSprite():void 
		{
			super.createSprite();
			m_sprite = new mcTeelo_Teemy();
		}
		
		override public function onCreate(lane:int, xPos:int, container:DisplayObjectContainer):void 
		{
			super.onCreate(lane, xPos, container);
			m_bashInitiated = false;
		}
		
		override public function attack(target:CBaseTeelos):void 
		{
			if ( !isCoolingDown() )
			{
				m_cooldownCounter = 0;
				m_sprite.gotoAndStop(4);	// teemy's second attack animation didn't look like attacking
				animationReset();
				
				target.damage(m_attack, this);
			}
			else
			{
				if( m_sprite.currentFrame != 1 )
				{
					m_sprite.gotoAndStop(1);
					animationReset();
				}
			}
		}
		
		public function set bashInitiated(value:Boolean):void
		{
			m_bashInitiated = value;
		}
		
		public function get bashInitiated():Boolean
		{
			return m_bashInitiated;
		}

	}//end CTeeloTeemy

}