///////////////////////////////////////////////////////////
//  CTeeloUztan.as
//  Macromedia ActionScript Implementation of the Class CTeeloUztan
//  Generated by Enterprise Architect
//  Created on:      11-Des-2010 22:25:05
//  Original author: poof!
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.ai.AIState;
	import com.game.CEnemyTeelos;

	/**
	 * @author poof!
	 * @version 1.0
	 * @created 11-Des-2010 22:25:05
	 */
	public class CTeeloUztan extends CEnemyTeelos
	{
		public function CTeeloUztan(){

		}
		
		override public function initialize():void 
		{
			super.initialize();
			
			m_attack = 1;
			m_defense = 1;
			m_maxLife = 8;
			m_unitClass = UNITCLASS.INFANTRY;
			m_counterClass = UNITCLASS.NONE;
			m_counterBonus = 0;
			m_baseSpeed = 0.05;
			m_dropMin = 0; //siom, 23jan011 12:28
			m_dropMax = 1;
			m_baseCooldownTime = 1200;
		}
		
		override protected function createSprite():void 
		{
			super.createSprite();
			m_sprite = new mcTeelo_Uztan();
		}
	}//end CTeeloUztan
}