///////////////////////////////////////////////////////////
//  CTeeloCaploztonCatapult.as
//  Macromedia ActionScript Implementation of the Class CTeeloCaploztonCatapult
//  Generated by Enterprise Architect
//  Created on:      05-Jan-2011 18:59:58
//  Original author: poof!
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.ai.AIState_Catapult_Enter;
	import com.game.CEnemyTeelos;
	import flash.display.DisplayObjectContainer;

	/**
	 * @author poof!
	 * @version 1.0
	 * @created 05-Jan-2011 18:59:58
	 */
	public class CTeeloCaploztonCatapult extends CEnemyTeelos implements IInvulnerable
	{
		private var m_readyThrow:Boolean;
		private var m_throwCounter:int;
		
		
		public function CTeeloCaploztonCatapult(){
		}
		
		override public function initialize():void 
		{
			super.initialize();
			
			m_attack = 0;
			m_defense = 1;
			m_maxLife = 100;
			m_unitClass = UNITCLASS.SIEGE;
			m_counterClass = UNITCLASS.NONE;
			m_counterBonus = 0;
			m_baseSpeed = 0.03;
			m_baseCooldownTime = 2000;
		}
	
		override protected function createSprite():void 
		{
			super.createSprite();
			m_sprite = new mcTeelo_Caplozton_Catapult();
		}
		
		override public function onCreate(lane:int, xPos:int, container:DisplayObjectContainer):void 
		{
			super.onCreate(lane, xPos, container);
			m_readyThrow = false;
			m_throwCounter = 0;
			setDestination(750);
			changeAIState(AIState_Catapult_Enter.getInstance());
		}
		
		public function readyThrow():void
		{
			m_readyThrow = true;
		}
		
		override public function update(elapsedTime:int):void 
		{
			super.update(elapsedTime);
			
			if ( m_readyThrow )
			{
				m_throwCounter += elapsedTime;
				if ( m_throwCounter > 450 )
				{
					NPCManager.getInstance().add(CTeeloCaplozton, m_lane, this.x, m_container);
					m_readyThrow = false;
				}
			}
		}
		
		override public function animationHit():void 
		{
			// do nothing
		}

	}//end CTeeloCaploztonCatapult

}