///////////////////////////////////////////////////////////
//  CTeeloFlagee.as
//  Macromedia ActionScript Implementation of the Class CTeeloFlagee
//  Generated by Enterprise Architect
//  Created on:      14-Jan-2011 10:58:00 AM
//  Original author: Kurniawan Fitriadi
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.CEnemyTeelos;
	import flash.display.DisplayObjectContainer;

	/**
	 * @author Kurniawan Fitriadi
	 * @version 1.0
	 * @created 14-Jan-2011 10:58:00 AM
	 */
	public class CTeeloFlagee extends CEnemyTeelos
	{
		public function CTeeloFlagee(){

		}
		
		override public function initialize():void 
		{
			super.initialize();
			
			m_defense = 8;
			m_unitClass = UNITCLASS.INFANTRY;
			m_counterClass = UNITCLASS.NONE;
			m_counterBonus = 0;
			m_baseSpeed = 0.035;
			m_dropMin = 3;
			m_dropMax = 4;
			m_baseCooldownTime = 6000;
			
			
		}
		
		override public function onCreate(lane:int, xPos:int, container:DisplayObjectContainer):void 
		{
			//play sfx
			SoundManager.getInstance().playSFX("SN17_2");
			
			m_attack = GlobalVars.getLevelGlobal() * 2.5;
			m_maxLife = GlobalVars.getLevelGlobal() * 3;
			
			super.onCreate(lane, xPos, container);
		}
		
		override protected function createSprite():void 
		{
			super.createSprite();
			m_sprite = new mcTeelo_Flagee();
		}
		
	}//end CTeeloFlagee

}