///////////////////////////////////////////////////////////
//  CSummonedLevel02.as
//  Macromedia ActionScript Implementation of the Class CSummonedLevel02
//  Generated by Enterprise Architect
//  Created on:      19-Des-2010 17:41:27
//  Original author: poof!
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.ai.AIState;
	import com.game.CBaseTeelos;
	import com.game.CTeeloBaseSummoned;
	import flash.display.DisplayObjectContainer;
	import math.OpMath;

	/**
	 * @author poof!
	 * @version 1.0
	 * @created 19-Des-2010 17:41:27
	 */
	public class CTeeloSummonedLevel02 extends CTeeloBaseSummoned
	{
		public function CTeeloSummonedLevel02(){

		}
		
		override public function initialize():void 
		{
			super.initialize();
			
			m_attack = 20;
			m_defense = 0;
			m_maxLife = 40;
			m_unitClass = UNITCLASS.SUMMON;
			m_counterClass = UNITCLASS.NONE;
			m_counterBonus = 0;
			m_baseSpeed = 0.042;
			m_baseCooldownTime = 4000;
			
			
		}
		
		override protected function createSprite():void 
		{
			super.createSprite();
			m_sprite = new mcTeelo_Summon_Lvl02();
		}
		
		override public function attack(target:CBaseTeelos):void 
		{
			super.attack(target);
		}
	}//end CSummonedLevel02

}